placeholders:
    placeholders:
        oro_account_channel_info_commerce:
            items:
                oro_account_customers_info: ~

    items:
        oro_account_customers_info:
            action: Oro\Bridge\CustomerAccount\Controller\CustomerController::accountCustomersInfoAction
