services:
    oro_customer_sales.provider.customer.customer_icon:
        class: Oro\Bridge\CustomerSales\Provider\Customer\CustomerIconProvider
        tags:
            - { name: oro_sales.customer_icon, priority: 10 }

    oro_customer_sales.customer_virtual_relations.provider:
        class: Oro\Bundle\SalesBundle\Provider\CustomerAssignmentVirtualRelationProvider
        public: false
        arguments:
            - 'Oro\Bundle\CustomerBundle\Entity\Customer'
        tags:
           - { name: oro_entity.virtual_relation_provider, priority: 150 }
